### PR TITLE
workflow: GerritReview: remove deprecated label/score attributes

### PR DESCRIPTION
**Pull request by alonbl**
Pending 0.4

### CODE REVIEW

**Comment by lucamilanesio** [comment]
@alonbl because of the video of the presentation of the presentation is now [published on YouTube](https://youtu.be/pyPMeCW-Q5k) I would prefer to delay the removal of these shortcuts to a later release. Otherwise, the people that will start using the plugin because they've watched the video would all of the sudden get something that isn't working at all.

**Comment by alonbl** [comment]
Please keep this open to the time you want to merge.

**Comment by lucamilanesio** [comment]
> Please keep this open to the time you want to merge.

Sounds good, however, bear in mind that it will need some rebasing later on ;-)

**Comment by lucamilanesio** [comment]
Review imported to GerritHub (https://review.gerrithub.io/c/jenkinsci/gerrit-code-review-plugin/+/409171)

**Pull request closed without merging**
