### PR TITLE
Bugfix/avoid println in tests

### PR DESCRIPTION
**Pull request by lucamilanesio**

### CODE REVIEW

**Comment by alonbl** [comment]
the reformat should be in own pull request, please also add a maven target to reformat and verify format to avoid this in future, I was not sure what format do you use.

for the print, why don't you want to print the long? I see that jenkins prints the long only for failed jobs.

**Comment by lucamilanesio** [comment]
> the reformat should be in own pull request

It is already two separate commits. With regards to creating two chained PRs (one depends from the other), GitHub doesn't support the use-case, that's why the only way is to have a single PR with two commits.

Will, hopefully, Mr. Microsoft implement it now?

> please also add a maven target to reformat and verify format to avoid this in future, I was not sure what format do you use.

Have you read [the project contribution guidelines](https://github.com/jenkinsci/gerrit-code-review-plugin/blob/master/CONTRIBUTING.md#formatting)? It is google-java-format.

Having a maven target is a good idea, I believe @ssbarnea proposed something already, just did not have time to implement it yet 😢 

> for the print, why don't you want to print the long? I see that Jenkins prints the long only for failed jobs.

We just have a few tests, it is fine for now. But if tests start generating tons of printouts, the Jenkins job output will become huge very quickly and ... what is the developer supposed to do?
Tests are not written for a developer to visually browse the logs: tests should say *yes* or *no*. That's it.

If assertions are well written when they fail they tell the reason for the failure. The `System.out.println()` I believe was a leftover of my nightly rush of getting the plugin released for the JenkinsWorld Conference in Nice 😢 apologies for the noise.

**Comment by lucamilanesio** [comment]
> BTW: can you please consider clone and create private branches instead of pushing temporary ones into upstream repo? I believe this is the best practice.

I really hate the GitHub workflow 👎 because forces me to create branches I don't need. The best practice is just NOT to use GitHub at all, creating a fork and private branches forces me to have even more pain. Is too noisy for you to have a branch that lasts for a few days and then goes away? I could call that branch refs/changes/NNNN where NNNN is just an incremental number 😄

**Comment by lucamilanesio** [comment]
Rebased now on master and with a single commit.
P.S. @alonbl I had to push an urgent fix to master because one important use-case was broken (simple SCM build with anonymous identity) and release the v0.3.2

**Comment by alonbl** [comment]
> P.S. @alonbl I had to push an urgent fix to master because one important use-case was broken (simple SCM build with anonymous identity) and release the v0.3.2

This is not the way to go, you need to open a stable branch per y-stream so that you can release z-stream without impact of master.

**Comment by ssbarnea** [comment]
I share the same hate regarding PR, and only because i used both PR and CR but I doubt we can do something about it now.

Regarding multiple branches: this would add extra maintenance efforths and based on the project size, number of contributors and users and its free nature.... it would sound like a bad idea.

**Comment by lucamilanesio** [comment]
I tend to agree that stable branches are good but when the project is in a more advanced state. Shall we start a stable-1.0 once we have a 1.0? (See the roadmap in the wiki)

At this stage the project is still too small and volatile to start dealing with stable branches, as @ssbarnea mentioned

**Pull request merged**
