### PR TITLE
gerritComment: allow creating comments associated with a range

### PR DESCRIPTION
**Pull request by francoisferrand**
Range is specified through the location parameter, which can be set
either to a file, line or range:

 gerritComment location: file(), message: '...'
 gerritComment location: line(23), message: '...'
 gerritComment location: range(startLine: 3, endLine: 7), message: '...'

To ensure backwards compatibility, line can also still be set directly:

 gerritComment line: 23, message: '...'

### CODE REVIEW

**Comment by Typz** [comment]
can anybody please review/merge this?

**Comment by lucamilanesio** [comment]
> Hello! can anybody please review/merge this?
> @lucamilanesio maybe?

Thanks @Typz for your contribution. Can you please [create a change for review on GerritHub.io](https://github.com/jenkinsci/gerrit-code-review-plugin/blob/master/CONTRIBUTING.md)?

**Comment by Typz** [comment]
> > Hello! can anybody please review/merge this?
> > @lucamilanesio maybe?
> 
> Thanks @Typz for your contribution. Can you please [create a change for review on GerritHub.io](https://github.com/jenkinsci/gerrit-code-review-plugin/blob/master/CONTRIBUTING.md)?

Sure! Sorry I missed this, I will move the PR to gerrithub.

**Comment by francoisferrand** [comment]
Moved to https://review.gerrithub.io/c/jenkinsci/gerrit-code-review-plugin/+/510174

**Pull request closed without merging**
